### PR TITLE
Refactor basic DEA and FDH by class

### PR DESCRIPTION
**Pull request by JulianATA**
* This pr provides the refactored basic DEA and FDH
You can test the classes with fallowing codes:
## DEA
```python
import pandas as pd
import numpy as np

# import the package pystoned
from pystoned import DEA

# import Finnish electricity distribution firms data
url = 'https://raw.githubusercontent.com/ds2010/pyStoNED-Tutorials/master/Data/firms.csv'
df = pd.read_csv(url, error_bad_lines=False)

# output
y = df['Energy']

# inputs
x1 = df['OPEX']
x1 = np.asmatrix(x1).T
x2 = df['CAPEX']
x2 = np.asmatrix(x2).T
x = np.concatenate((x1, x2), axis=1)

model = DEA.DEA(y,x,"oo","vrs")
model.optimize(False)
model.display_theta()
```
## FDH
```python
import pandas as pd
import numpy as np

# import the package pystoned
from pystoned import FDH

# import Finnish electricity distribution firms data
url = 'https://raw.githubusercontent.com/ds2010/pyStoNED-Tutorials/master/Data/firms.csv'
df = pd.read_csv(url, error_bad_lines=False)

# output
y = df['Energy']

# inputs
x1 = df['OPEX']
x1 = np.asmatrix(x1).T
x2 = df['CAPEX']
x2 = np.asmatrix(x2).T
x = np.concatenate((x1, x2), axis=1)

model = FDH.FDH(y,x,"oo")
model.optimize(False)
model.display_theta()
```

* The results are identical to the original codes.
* The StoNED + CNLSDDF has been implemented, however it is a little bit complicated.
    * To reduce the complexity of StoNED + CNLSDDF, I'm recently working on `get_frontier` function.
    * The `get_frontier` function can make the implementation of StoNED/StoNED+DDF more consistency.

### CODE REVIEW

**Comment by ds2010** [comment]
OK. The FDH class looks very nice. But it seems that the new DEA class does not include the functions DDF, bad output, and projection. How do you think?

**Comment by JulianATA** [comment]
@ds2010, thanks for your quick reply.
The DDF, bad output, and projection will be implemented.
Basically, it is 2 related methodologies.
Since they are both able to consider about bad output, I'm trying to make this 2 more consistent and easy to use.

**Comment by ds2010** [comment]
Ideally, I think `ddf` is one of the orient selections. That means `orient =` could be  "io", "oo", and "ddf". Regarding the projection, I think if the user does not define the benchmark technology (`Xref`, `Yref`), then `Xref` = x and `Yref`= y. This is a default argument. Otherwise, we have to consider the reference points (`Xref`, `Yref`) in the code.

Indeed, the bad output could be a separate case.

**Comment by ds2010** [comment]
Here is an example of how to merge the reference points into the DEA class in Julia.

https://github.com/javierbarbero/DataEnvelopmentAnalysis.jl/blob/master/src/dea.jl

**Comment by JulianATA** [comment]
I see. Since all of the DEA variants are multiple input/output, we should indeed implement them together.
I'll implement DDF/projection expanding the DEA class.
Thanks for the reference provided!

**Comment by ds2010** [comment]
Yes, I am writing an additional suggestion, I guess we can even integrate the argument `b` into the DEA class, for example, `__init__(self, y, x, b=None, Xref = None, Yref = None, orient, rts)`, right?

**Comment by JulianATA** [comment]
Just a slightly change:
__init__(self, y, x, b=None, Xref = None, Yref = None, orient="oo", rts="vrs")
The `orient` and `rts` are following parameter with default value, they should have default value too.

**Pull request merged**
